{  
   "emailRecipients":[  
      "testAsdaSmartComms@gmail.com"
   ],
   "payload":{  
      "emailPayload":{  
         "images":{  
            "asdaLogo":"http://i.groceries.asda.com:80/assets/img/email/asda_logo_new.png",
            "dpEmailFooter":null,
            "dpLogo":"http://i.groceries.asda.com:80/assets/img/email/white_logo.png",
            "logoImagePath":null,
            "lorryImagePath":null,
            "emailFooterLogo":"http://i.groceries.asda.com:80/assets/img/email/dp-emailer-footer-logo.jpg",
            "dpEmailCheckNowImg":null,
            "dpVanImg":null,
            "visitAsdaImg":null,
            "dpBoughtImg":null,
            "dotImg":null,
            "bgBottomImg":null,
            "personalDetailsLogo":null,
            "asdaThanksImg":"http://i.groceries.asda.com:80/assets/img/email/thanks.gif",
            "asdaLadyImg":null,
            "yourQRCodeImg":null
         },
         "asdaSiteUrls":{  
            "asdaURL":null,
            "amendOrderURL":null,
            "dpURL":null,
            "dpDashBoardURL":null,
            "recurringSlotPgURL":null,
            "asdaAccountsURL":null,
            "asdaOrderURL":"https://groceries.asda.com:443/account/orders",
            "yourQRcodeURL":null,
            "asdaMobAppURL":null,
            "custHelpPage":null,
            "asdaTnCPage":null,
            "evoucherPage":null
         },
         "order":{  
            "orderId":"123456789",
            "commerceItemsList":null,
            "refundItemsList":null,
            "firstOrder":null,
            "fulfillmentType":null,
            "storeId":null,
            "shipOnDate":null,
            "shipOnDateWithoutYear":null,
            "orderAuthStatus":null,
            "creditCardNumber":null,
            "priceInfo":null,
            "directions":null,
            "storeAddress":null,
            "amendedOrder":null,
            "fullAuthEnabled":null
         },
         "dp":null,
         "profile":{  
            "profileId":null,
            "firstName":"TestOrder",
            "fullName":null,
            "emailId":"testAsdaSmartComms@gmail.com",
            "voucherAmount":null,
            "promotionType":null,
            "regPwdResetUrl":null
         },
         "slot":null,
         "dynamicSubject":null,
         "currentYear":null
      }
   },
   "messageId":"123456789-16094648827391152",
   "smsRecipients":null,
   "appNotificationRecipients":null,
   "customerId":null,
   "eventInfo":{  
      "tenant":"5",
      "vertical":"2",
      "team":"CS",
      "event":"cancelOrderEmail",
      "eventType":"default"
   },
   "locale":null,
   "template":null,
   "sendPlaintext":false,
   "recommendations":null,
   "emailAttachments":null,
   "emailSent":null,
   "smsSent":null,
   "appNotificationSent":null,
   "headerOne":null,
   "headerTwo":null,
   "headerThree":null,
   "headerFour":null
}